import ast

content = open("scripts/api.py", encoding="utf-8").read()

start_marker = "    def predict_batch_from_dataframe"
end_marker   = "    def get_cluster_profiles"
i = content.find(start_marker)
j = content.find(end_marker)
assert i != -1 and j != -1, "Markers not found"
print(f"Replacing bytes {i}..{j}")

new_method = r"""    def predict_batch_from_dataframe(self, df: "pd.DataFrame") -> "pd.DataFrame":
        """
new_method = (
    '    def predict_batch_from_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:\n'
    '        """\n'
    '        Prediction en lot vectorisee depuis un DataFrame brut (niveau commande).\n'
    '\n'
    '        Optimisation : au lieu d\'appeler predict_segment() une fois par client\n'
    '        (couteux : logs + appels sklearn separes), cette methode applique le\n'
    '        pipeline complet (QT -> Scaler -> PCA -> KMeans) en UNE SEULE operation\n'
    '        matricielle sur tous les clients (~100x plus rapide en lot).\n'
    '\n'
    '        Colonnes requises  : customer_unique_id, order_id, order_status,\n'
    '                             order_purchase_timestamp, payment_value\n'
    '        Colonnes optionnelles : payment_installments,\n'
    '                                order_delivered_customer_date, review_score\n'
    '        """\n'
    '        if "customer_unique_id" not in df.columns:\n'
    '            raise ValueError(\n'
    '                "Le fichier CSV doit contenir une colonne \'customer_unique_id\'."\n'
    '            )\n'
    '\n'
    '        feature_cols    = self.pipeline["feature_cols"]\n'
    '        qt              = self.pipeline["quantile_transformer"]\n'
    '        scaler          = self.pipeline["scaler"]\n'
    '        pca             = self.pipeline["pca"]\n'
    '        model           = self.pipeline["model"]\n'
    '        cluster_names   = self.pipeline["cluster_names"]\n'
    '        segment_actions = self.pipeline["segment_actions"]\n'
    '        qt_min = qt.quantiles_[0, :]\n'
    '        qt_max = qt.quantiles_[-1, :]\n'
    '\n'
    '        # ---- Phase 1 : calcul des features (boucle legere, sans sklearn) ----\n'
    '        groups = df.groupby("customer_unique_id", sort=False)\n'
    '        total  = len(groups)\n'
    '        logger.info(f"Batch vectorise : {total} clients detectes.")\n'
    '\n'
    '        client_ids    = []\n'
    '        n_orders_list = []\n'
    '        feat_rows     = []\n'
    '        error_rows    = []\n'
    '\n'
    '        for cid, group in groups:\n'
    '            orders = group.to_dict(orient="records")\n'
    '            for o in orders:\n'
    '                o["customer_unique_id"] = cid\n'
    '            try:\n'
    '                features = self._compute_features_from_orders(orders)\n'
    '                client_ids.append(cid)\n'
    '                n_orders_list.append(len(orders))\n'
    '                feat_rows.append(features)\n'
    '            except Exception as e:\n'
    '                logger.warning(f"Echec features pour client {cid}: {e}")\n'
    '                error_rows.append({\n'
    '                    "customer_unique_id": cid,\n'
    '                    "n_orders": len(orders),\n'
    '                    "Recency": None, "avg_review_score_full": None,\n'
    '                    "avg_delivery_days": None, "avg_installments": None,\n'
    '                    "CLV_estimate": None,\n'
    '                    "cluster": -1, "segment_name": "Erreur",\n'
    '                    "segment_action": str(e), "confidence": None,\n'
    '                })\n'
    '\n'
    '        good_rows = []\n'
    '        if feat_rows:\n'
    '            # ---- Phase 2 : pipeline vectorise sur toute la matrice ----\n'
    '            X = np.array(\n'
    '                [[f[c] for c in feature_cols] for f in feat_rows],\n'
    '                dtype=np.float64\n'
    '            )\n'
    '            X = np.clip(X, qt_min, qt_max)\n'
    '\n'
    '            import warnings\n'
    '            with warnings.catch_warnings():\n'
    '                warnings.simplefilter("ignore")\n'
    '                X_qt     = qt.transform(X)\n'
    '                X_scaled = scaler.transform(X_qt)\n'
    '                X_pca    = pca.transform(X_scaled)\n'
    '\n'
    '            X_pred   = X_pca.astype(model.cluster_centers_.dtype, copy=False)\n'
    '            clusters = model.predict(X_pred)\n'
    '\n'
    '            centers = model.cluster_centers_\n'
    '            dists   = np.linalg.norm(\n'
    '                X_pred[:, np.newaxis, :] - centers[np.newaxis, :, :], axis=2\n'
    '            )\n'
    '            assigned_dists = dists[np.arange(len(clusters)), clusters]\n'
    '            confidences    = 1.0 / (1.0 + assigned_dists)\n'
    '\n'
    '            logger.info(f"Pipeline vectorise applique sur {len(feat_rows)} clients.")\n'
    '\n'
    '            for cid, n_ord, feats, clust, conf in zip(\n'
    '                client_ids, n_orders_list, feat_rows, clusters, confidences\n'
    '            ):\n'
    '                good_rows.append({\n'
    '                    "customer_unique_id": cid,\n'
    '                    "n_orders": n_ord,\n'
    '                    **feats,\n'
    '                    "cluster": int(clust),\n'
    '                    "segment_name": cluster_names.get(int(clust), f"Cluster {clust}"),\n'
    '                    "segment_action": segment_actions.get(int(clust), "Standard"),\n'
    '                    "confidence": round(float(conf), 4),\n'
    '                })\n'
    '\n'
    '        result_df = pd.DataFrame(good_rows + error_rows)\n'
    '        ordered_cols = [\n'
    '            "customer_unique_id", "n_orders",\n'
    '            "Recency", "avg_review_score_full", "avg_delivery_days",\n'
    '            "avg_installments", "CLV_estimate",\n'
    '            "cluster", "segment_name", "segment_action", "confidence",\n'
    '        ]\n'
    '        result_df = result_df[[c for c in ordered_cols if c in result_df.columns]]\n'
    '        logger.info(f"Batch terminee : {len(result_df)} clients.")\n'
    '        return result_df\n'
    '\n'
)

new_content = content[:i] + new_method + content[j:]
open("scripts/api.py", "w", encoding="utf-8").write(new_content)
print("Fichier ecrit.")

# Verification syntaxe
ast.parse(new_content)
print("Syntax OK")
print(f"Taille fichier : {len(new_content)} caracteres")
